### ISSUE TITLE
Hi! How to contact you? We are also writing WinUI3/UWP applications, can we communicate?

### ISSUE THREAD

**Issue by Shomnipotence** [Lixkote/Startify#2]
Hi! How to contact you? We are also writing WinUI3/UWP applications, can we communicate?

**Comment by jaqczk37** [comment]
In order to communicate with Lixkote you have to send a carrier pigeon with Your message.

**Comment by arin2115** [comment]
@jaqczk37, Lixkote prefers TCP communication by using IPoAC, it's more secure.

**Comment by Maks1116** [comment]
> In order to communicate with Lixkote you have to send a carrier pigeon with Your message.

But you can't just use carrier pidgeons for that. Due to a lot of spam coming to Lix recently, he asked me to develop a captcha solution for him. Before you send any message for him, print this and check the box to confirm, that you're not a robot:

![elocaptcha](https://github.com/Lixkote/Startify/assets/44298626/a77c4a5f-8104-41fb-b269-2b1c4bc32053)

By the way Lix prefers to talk to him over TCP using IPoAC.

**Comment by Lixkote** [comment]
> Hi! How to contact you? We are also writing WinUI3/UWP applications, can we communicate?

Sorry for late response, you can contact me on discord at the name 'lixkote'
